/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Doutor } from './doutor';
import { Paciente } from './paciente';
import { Usuario } from './usuario';


export interface Consulta { 
    doutor?: Doutor;
    id?: number;
    paciente?: Paciente;
    usuario?: Usuario;
}
